language: ruby
script: "rake spec:all"
rvm:
  - jruby-1.7.16
  - jruby-head
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
matrix:
  allow_failures:
    - rvm: jruby-head
  fast_finish: true
notifications:
  irc: "irc.freenode.org#shoes"
  email:
    recipients:
      - davor@davor.se
      - wasnotrice@gmail.com
      - tobias.pfeiffer@student.hpi.uni-potsdam.de
      - ashbbb@gmail.com
      - james@jamesrgifford.com
      - peter.fitzgibbons@gmail.com
      - fism88@gmail.com
      - jason@jasonrclark.net
    on_success: change # [always|never|change] # default: change
    on_failure: change # [always|never|change] # default: always
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
after_script:
  - find -name '*.log' -exec cat {} \;
addons:
  code_climate:
    repo_token: 45d4f3c5c1de9031011acf4c3c85867f152cea4200c61f3b69d881bcf2794e9f
