install:
  - appveyor DownloadFile https://s3.amazonaws.com/jruby.org/downloads/9.1.6.0/jruby-bin-9.1.6.0.zip
  - 7z x jruby-bin-9.1.6.0.zip -y
  - SET PATH=C:\projects\shoes4\jruby-9.1.6.0\bin;%PATH%
  - gem install bundler
  - bundle

build: off

shallow_clone: true

test_script:
  - rubocop
  - rake spec:shoes
